### PR TITLE
fix: Skip returning EOS token on finish_reason 'stop'

### LINKED ISSUE #276: OpenAI Stream Format Bug with Mistral Models
### System Info

latest version

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Deploy Lorax with Docker, using `--model-id mistralai/Mistral-7B-Instruct-v0.1` 
2. Make request to Open Ai Compatible endpoints, set `"stream": true`
```
{
    "model": "",
    "messages": [
        {
            "role": "user",
            "content": "Hi"
        }
    ],
    "stream": true
}
```

3. Recieve excessive stream end token `</s>`

```
data:{"id":"null","object":"chat.completion.chunk","created":0,"model":"null","choices":[{"index":0,"delta":{"role":"assistant","content":" today"},"finish_reason":null}]}

data:{"id":"null","object":"chat.completion.chunk","created":0,"model":"null","choices":[{"index":0,"delta":{"role":"assistant","content":"?"},"finish_reason":null}]}

data:{"id":"null","object":"chat.completion.chunk","created":0,"model":"null","choices":[{"index":0,"delta":{"role":"assistant","content":"</s>"},"finish_reason":"stop"}]}
```

### Expected behavior

The stream end without Mistral end token `</s>` and have [DONE]

```
data: {"id":"chatcmpl-8vUECL9h8rhRQADqTNpuuwBmtxhpL","object":"chat.completion.chunk","created":1708711584,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_86156a94a0","choices":[{"index":0,"delta":{"content":" today"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8vUECL9h8rhRQADqTNpuuwBmtxhpL","object":"chat.completion.chunk","created":1708711584,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_86156a94a0","choices":[{"index":0,"delta":{"content":"?"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8vUECL9h8rhRQADqTNpuuwBmtxhpL","object":"chat.completion.chunk","created":1708711584,"model":"gpt-3.5-turbo-0125","system_fingerprint":"fp_86156a94a0","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}

data: [DONE]
```

### PR DESCRIPTION
**Pull request by jeffreyftang**
Fixes #276 

Tested manually using OpenAI client against both a LoRAX instance and live OpenAI API. For chat completions, both now yield 

```Choice(delta=ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=None)```

as the last message.

For legacy completions, both now yield:

```
CompletionChoice(finish_reason='stop', index=0, logprobs=None, text='')
```

### CODE REVIEW

**Comment by tgaddair** [comment]
Looks like tests are failing deterministically at the moment. Can you take a look?

**Comment by jeffreyftang** [comment]
I think it's due to the HF outage. The failure's coming from a function to instantiate a tokenizer from HF.

**Comment by jeffreyftang** [comment]
Tests passed on re-run now that HF is back.

**Comment by martindavis** [comment]
@jeffreyftang , is this the `</s>` token I see when the streaming is finished? Just to confirm, we'll still send back the stats with this change, but won't send back the token?

**Review by tgaddair — APPROVED** [review]

**Pull request merged**
