### PR TITLE
Ensuring adapters get downloaded in the correct directory from S3

### LINKED ISSUE #236: S3 Adapter Loading Failing
### System Info

ghcr.io/predibase/lorax:87412e1

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Getting Same Error even after providing fix on #234

Docker Logs:
2024-02-11T09:09:19.286855Z  INFO lorax_router::loader: router/src/loader.rs:150: adapter s3:s3://adapters/gsm8k downloaded
2024-02-11T09:09:19.286896Z  INFO lorax_router::queue: router/src/queue.rs:135: set adapter s3:s3://adapters/gsm8k status to Downloaded
2024-02-11T09:09:19.293490Z ERROR lorax_client: router/client/src/lib.rs:34: Server error: Can't find 'adapter_config.json' at '/data/models--s3:----adapters--gsm8k/snapshots'
2024-02-11T09:09:19.293526Z  INFO lorax_router::loader: router/src/loader.rs:206: FAILED loading adapter s3:s3://adapters/gsm8k
2024-02-11T09:09:19.293550Z  INFO lorax_router::queue: router/src/queue.rs:135: set adapter s3:s3://adapters/gsm8k status to Errored
2024-02-11T09:09:19.293624Z  INFO lorax_router::loader: router/src/loader.rs:276: terminating adapter s3:s3://adapters/gsm8k loader

### Expected behavior

S3 Adapter Loading should work properly

### PR DESCRIPTION
**Pull request by DhruvaBansal00**
# What does this PR do?

 S3 paths to the adapter are reconstructed because we overwrite model_id with the prefix to the model without the path. We can't replace self.model_id with the complete path since that is used downstream as a prefix to read contents.

Fixes #236.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Was this discussed/approved via a Github issue or the discord / slack channel? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?

## Who can review?

@tgaddair

### CODE REVIEW

**Comment by magdyksaleh** [comment]
@jeffreyftang to review

**Comment by DhruvaBansal00** [comment]
Actually, I don't think we need this PR anymore. The change by @jeffreyftang yesterday fixed loading adapters from S3 paths.

**Comment by jeffreyftang** [comment]
Ah, thanks for the clarification! I'll go ahead and close the PR and attached issue shortly if there are no objections :)

**Comment by DhruvaBansal00** [comment]
Yep sounds good!

**Pull request closed without merging**
